[package]
name = "commonlibsse_ng"
authors = ["SARDONYX"]
description = "CommonLibSSE-NG Rust bindings"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"


[[example]]
name = "module_state"
crate-type = ["cdylib"]
path = "./examples/module_state.rs"
required-features = ["full"]


[dependencies]
bitflags = { version = "2.9.0" }
chrono = { version = "0.4.40" }
dashmap = { version = "6.1.0" }
generic-array = { version = "1.2.0" }
num-traits = { version = "0.2.19" }
once_cell = { workspace = true }
retour = { version = "0.3.1", default-features = false }     # fn ptr hook
shared_rwlock = { path = "../shared_rwlock" }
snafu = { workspace = true }                                 # To define error types.
static_assertions = { workspace = true }                     # Compile tim assertions
tracing = { workspace = true, optional = true }
tracing-appender = { version = "0.2.3", optional = true }
tracing-subscriber = { version = "0.3.19", optional = true }
typenum = { version = "1.18.0" }
unique = "0.9.1"                                             # Owned raw pointer(Used in std but not provided as API)

commonlibsse_ng_derive_internal = { path = "../commonlibsse_ng_derive_internal" }
commonlibsse_ng_derive = { path = "../commonlibsse_ng_derive", optional = true }


[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
  "Win32_Devices_HumanInterfaceDevice",
  "Win32_Globalization",
  "Win32_Graphics_Direct3D11",
  "Win32_Security",
  "Win32_Storage_FileSystem",
  "Win32_System_Com",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Environment",
  "Win32_System_Kernel",
  "Win32_System_LibraryLoader",
  "Win32_System_Memory",
  "Win32_System_ProcessStatus",
  "Win32_System_Registry",
  "Win32_System_SystemInformation",
  "Win32_System_SystemServices",
  "Win32_System_Threading",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_Input_XboxController",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }


[dev-dependencies]
pretty_assertions = "1.4.1"


[features]
# default = ["full", "test_on_local"] # To debug

# Enable tracing log support
tracing = [
  "dep:tracing",
  "dep:tracing-subscriber",
  "dep:tracing-appender",
  "commonlibsse_ng_derive_internal/tracing",
  "commonlibsse_ng_derive?/tracing",
]

# For local test(Address library test)
test_on_local = ["tracing"]

# For test on CI
test_on_ci = ["tracing"]

# Enable proc macro
derive = ["dep:commonlibsse_ng_derive"]

full = ["tracing", "derive", "commonlibsse_ng_derive/tracing"]


[lints]
workspace = true
