[package]
name = "commonlibsse_ng_sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"

[build-dependencies]
bindgen = { version = "0.69.5", optional = true }
vcpkg = "0.2.15"

[features]
generate = ["dep:bindgen"]
