[package]
name = "commonlibsse_ng_derive"
description = "Useful attribute macros for commonlibsse_ng"
version = "0.1.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme = "./readme.md"
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]
darling = "0.20.10"
proc-macro2 = { version = "1.0.94" }
quote = { version = "1.0.39" }
syn = { version = "2.0.99" }

[features]
tracing = []
