//! This is a Rust reimplementation of CommonLibSSE-NG.
//!
//! It is intended to be memory-safe using the power of Rust.
//!
//! - sys: C++ binding (when no_sys feature is disabled): This is enabled by default.
//!   However, currently the types generated by rust-bindgen are difficult to use, and since
//!   the inline function does not exist in the .lib, only the inline function can be called.

#![allow(clippy::approx_constant)]
#![allow(clippy::excessive_precision)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::transmute_int_to_bool)]
#![allow(clippy::useless_transmute)]
#![allow(improper_ctypes)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(renamed_and_removed_lints)]

include!("./bindings.rs");
