bitflags::bitflags! {
    #[derive(Debug, Copy, Clone, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct ExtraDataType: u32 {
        /// 0x00
        const None = 0x00;
        /// 0x01 - ExtraHavok
        const Havok = 0x01;
        /// 0x02 - ExtraCell3D
        const Cell3D = 0x02;
        /// 0x03 - ExtraCellWaterType
        const CellWaterType = 0x03;
        /// 0x04 - ExtraRegionList
        const RegionList = 0x04;
        /// 0x05 - ExtraSeenData
        const SeenData = 0x05;
        /// 0x06 - ExtraEditorID
        const EditorID = 0x06;
        /// 0x07 - ExtraCellMusicType
        const CellMusicType = 0x07;
        /// 0x08 - ExtraCellSkyRegion
        const CellSkyRegion = 0x08;
        /// 0x09 - ExtraProcessMiddleLow
        const ProcessMiddleLow = 0x09;
        /// 0x0A - ExtraDetachTime
        const DetachTime = 0x0A;
        /// 0x0B - ExtraPersistentCell
        const PersistentCell = 0x0B;
        /// 0x0C
        const Unk0C = 0x0C;
        /// 0x0D - ExtraAction
        const Action = 0x0D;
        /// 0x0E - ExtraStartingPosition
        const StartingPosition = 0x0E;
        /// 0x0F
        const Unk0F = 0x0F;
        /// 0x10 - ExtraAnimGraphManager
        const AnimGraphManager = 0x10;
        /// 0x11 - ExtraBiped
        const Biped = 0x11;
        /// 0x12 - ExtraUsedMarkers
        const UsedMarkers = 0x12;
        /// 0x13 - ExtraDistantData
        const DistantData = 0x13;
        /// 0x14 - ExtraRagDollData
        const RagDollData = 0x14;
        /// 0x15 - ExtraContainerChanges
        const ContainerChanges = 0x15;
        /// 0x16 - ExtraWorn
        const Worn = 0x16;
        /// 0x17 - ExtraWornLeft
        const WornLeft = 0x17;
        /// 0x18 - ExtraPackageStartLocation
        const PackageStartLocation = 0x18;
        /// 0x19 - ExtraPackage
        const Package = 0x19;
        /// 0x1A - ExtraTresPassPackage
        const TresPassPackage = 0x1A;
        /// 0x1B - ExtraRunOncePacks
        const RunOncePacks = 0x1B;
        /// 0x1C - ExtraReferenceHandle
        const ReferenceHandle = 0x1C;
        /// 0x1D - ExtraFollower
        const Follower = 0x1D;
        /// 0x1E - ExtraLevCreaModifier
        const LevCreaModifier = 0x1E;
        /// 0x1F - ExtraGhost
        const Ghost = 0x1F;
        /// 0x20 - ExtraOriginalReference
        const OriginalReference = 0x20;
        /// 0x21 - ExtraOwnership
        const Ownership = 0x21;
        /// 0x22 - ExtraGlobal
        const Global = 0x22;
        /// 0x23 - ExtraRank
        const Rank = 0x23;
        /// 0x24 - ExtraCount
        const Count = 0x24;
        /// 0x25 - ExtraHealth
        const Health = 0x25;
        /// 0x26
        const Unk26 = 0x26;
        /// 0x27 - ExtraTimeLeft
        const TimeLeft = 0x27;
        /// 0x28 - ExtraCharge
        const Charge = 0x28;
        /// 0x29 - ExtraLight
        const Light = 0x29;
        /// 0x2A - ExtraLock
        const Lock = 0x2A;
        /// 0x2B - ExtraTeleport
        const Teleport = 0x2B;
        /// 0x2C - ExtraMapMarker
        const MapMarker = 0x2C;
        /// 0x2D - ExtraLeveledCreature
        const LeveledCreature = 0x2D;
        /// 0x2E - ExtraLeveledItem
        const LeveledItem = 0x2E;
        /// 0x2F - ExtraScale
        const Scale = 0x2F;
        /// 0x30 - ExtraMissingLinkedRefIDs
        const MissingLinkedRefIDs = 0x30;
        /// 0x31 - ExtraMagicCaster
        const MagicCaster = 0x31;
        /// 0x32 - NonActorMagicTarget
        const NonActorMagicTarget = 0x32;
        /// 0x33
        const Unk33 = 0x33;
        /// 0x34 - ExtraPlayerCrimeList
        const PlayerCrimeList = 0x34;
        /// 0x35
        const Unk35 = 0x35;
        /// 0x36 - ExtraEnableStateParent
        const EnableStateParent = 0x36;
        /// 0x37 - ExtraEnableStateChildren
        const EnableStateChildren = 0x37;
        /// 0x38 - ExtraItemDropper
        const ItemDropper = 0x38;
        /// 0x39 - ExtraDroppedItemList
        const DroppedItemList = 0x39;
        /// 0x3A - ExtraRandomTeleportMarker
        const RandomTeleportMarker = 0x3A;
        /// 0x3B
        const Unk3B = 0x3B;
        /// 0x3C - ExtraSavedHavokData
        const SavedHavokData = 0x3C;
        /// 0x3D - ExtraCannotWear
        const CannotWear = 0x3D;
        /// 0x3E - ExtraPoison
        const Poison = 0x3E;
        /// 0x3F - ExtraMagicLight
        const MagicLight = 0x3F;
        /// 0x40 - ExtraLastFinishedSequence
        const LastFinishedSequence = 0x40;
        /// 0x41 - ExtraSavedAnimation
        const SavedAnimation = 0x41;
        /// 0x42 - ExtraNorthRotation
        const NorthRotation = 0x42;
        /// 0x43 - ExtraSpawnContainer
        const SpawnContainer = 0x43;
        /// 0x44 - ExtraFriendHits
        const FriendHits = 0x44;
        /// 0x45 - ExtraHeadingTarget
        const HeadingTarget = 0x45;
        /// 0x46
        const Unk46 = 0x46;
        /// 0x47 - ExtraRefractionProperty
        const RefractionProperty = 0x47;
        /// 0x48 - ExtraStartingWorldOrCell
        const StartingWorldOrCell = 0x48;
        /// 0x49 - ExtraHotkey
        const Hotkey = 0x49;
        /// 0x4A - ExtraEditorRef3DData
        const EditorRef3DData = 0x4A;
        /// 0x4B - ExtraEditorRefMoveData
        const EditorRefMoveData = 0x4B;
        /// 0x4C - ExtraInfoGeneralTopic
        const InfoGeneralTopic = 0x4C;
        /// 0x4D - ExtraHasNoRumors
        const HasNoRumors = 0x4D;
        /// 0x4E - ExtraSound
        const Sound = 0x4E;
        /// 0x4F - ExtraTerminalState
        const TerminalState = 0x4F;
        /// 0x50 - ExtraLinkedRef
        const LinkedRef = 0x50;
        /// 0x51 - ExtraLinkedRefChildren
        const LinkedRefChildren = 0x51;
        /// 0x52 - ExtraActivateRef
        const ActivateRef = 0x52;
        /// 0x53 - ExtraActivateRefChildren
        const ActivateRefChildren = 0x53;
        /// 0x54 - ExtraCanTalkToPlayer
        const CanTalkToPlayer = 0x54;
        /// 0x55 - ExtraObjectHealth
        const ObjectHealth = 0x55;
        /// 0x56 - ExtraCellImageSpace
        const CellImageSpace = 0x56;
        /// 0x57 - ExtraNavMeshPortal
        const NavMeshPortal = 0x57;
        /// 0x58 - ExtraModelSwap
        const ModelSwap = 0x58;
        /// 0x59 - ExtraRadius
        const Radius = 0x59;
        /// 0x5A
        const Unk5A = 0x5A;
        /// 0x5B - ExtraFactionChanges
        const FactionChanges = 0x5B;
        /// 0x5C - ExtraDismemberedLimbs
        const DismemberedLimbs = 0x5C;
        /// 0x5D - ExtraActorCause
        const ActorCause = 0x5D;
        /// 0x5E - ExtraMultiBound
        const MultiBound = 0x5E;
        /// 0x5F - MultiBoundMarkerData
        const MultiBoundMarkerData = 0x5F;
        /// 0x60 - ExtraMultiBoundRef
        const MultiBoundRef = 0x60;
        /// 0x61 - ExtraReflectedRefs
        const ReflectedRefs = 0x61;
        /// 0x62 - ExtraReflectorRefs
        const ReflectorRefs = 0x62;
        /// 0x63 - ExtraEmittanceSource
        const EmittanceSource = 0x63;
        /// 0x64
        const Unk64 = 0x64;
        /// 0x65 - ExtraCombatStyle
        const CombatStyle = 0x65;
        /// 0x66
        const Unk66 = 0x66;
        /// 0x67 - ExtraPrimitive
        const Primitive = 0x67;
        /// 0x68 - ExtraOpenCloseActivateRef
        const OpenCloseActivateRef = 0x68;
        /// 0x69 - ExtraAnimNoteReceiver
        const AnimNoteReceiver = 0x69;
        /// 0x6A - ExtraAmmo
        const Ammo = 0x6A;
        /// 0x6B - ExtraPatrolRefData
        const PatrolRefData = 0x6B;
        /// 0x6C - ExtraPackageData
        const PackageData = 0x6C;
        /// 0x6D - ExtraOcclusionShape
        const OcclusionShape = 0x6D;
        /// 0x6E - ExtraCollisionData
        const CollisionData = 0x6E;
        /// 0x6F - ExtraSayTopicInfoOnceADay
        const SayTopicInfoOnceADay = 0x6F;
        /// 0x70 - ExtraEncounterZone
        const EncounterZone = 0x70;
        /// 0x71 - ExtraSayToTopicInfo
        const SayTopicInfo = 0x71;
        /// 0x72 - ExtraOcclusionPlaneRefData
        const OcclusionPlaneRefData = 0x72;
        /// 0x73 - ExtraPortalRefData
        const PortalRefData = 0x73;
        /// 0x74 - ExtraPortal
        const Portal = 0x74;
        /// 0x75 - ExtraRoom
        const Room = 0x75;
        /// 0x76 - ExtraHealthPerc
        const HealthPerc = 0x76;
        /// 0x77 - ExtraRoomRefData
        const RoomRefData = 0x77;
        /// 0x78 - ExtraGuardedRefData
        const GuardedRefData = 0x78;
        /// 0x79 - ExtraCreatureAwakeSound
        const CreatureAwakeSound = 0x79;
        /// 0x7A
        const Unk7A = 0x7A;
        /// 0x7B - ExtraHorse
        const Horse = 0x7B;
        /// 0x7C - ExtraIgnoredBySandbox
        const IgnoredBySandbox = 0x7C;
        /// 0x7D - ExtraCellAcousticSpace
        const CellAcousticSpace = 0x7D;
        /// 0x7E - ExtraReservedMarkers
        const ReservedMarkers = 0x7E;
        /// 0x7F - ExtraWeaponIdleSound
        const WeaponIdleSound = 0x7F;
        /// 0x80 - ExtraWaterLightRefs
        const WaterLightRefs = 0x80;
        /// 0x81 - ExtraLitWaterRefs
        const LitWaterRefs = 0x81;
        /// 0x82 - ExtraWeaponAttackSound
        const WeaponAttackSound = 0x82;
        /// 0x83 - ExtraActivateLoopSound
        const ActivateLoopSound = 0x83;
        /// 0x84 - ExtraPatrolRefInUseData
        const PatrolRefInUseData = 0x84;
        /// 0x85 - ExtraAshPileRef
        const AshPileRef = 0x85;
        /// 0x86 - ExtraCreatureMovementSound
        const CreatureMovementSound = 0x86;
        /// 0x87 - ExtraFollowerSwimBreadcrumbs
        const FollowerSwimBreadcrumbs = 0x87;
        /// 0x88 - ExtraAliasInstanceArray
        const AliasInstanceArray = 0x88;
        /// 0x89 - ExtraLocation
        const Location = 0x89;
        /// 0x8A
        const Unk8A = 0x8A;
        /// 0x8B - ExtraLocationRefType
        const LocationRefType = 0x8B;
        /// 0x8C - ExtraPromotedRef
        const PromotedRef = 0x8C;
        /// 0x8D - ExtraAnimationSequencer
        const AnimationSequencer = 0x8D;
        /// 0x8E - ExtraOutfitItem
        const OutfitItem = 0x8E;
        /// 0x8F
        const Unk8F = 0x8F;
        /// 0x90 - ExtraLeveledItemBase
        const LeveledItemBase = 0x90;
        /// 0x91 - ExtraLightData
        const LightData = 0x91;
        /// 0x92 - ExtraSceneData
        const SceneData = 0x92;
        /// 0x93 - ExtraBadPosition
        const BadPosition = 0x93;
        /// 0x94 - ExtraHeadTrackingWeight
        const HeadTrackingWeight = 0x94;
        /// 0x95 - ExtraFromAlias
        const FromAlias = 0x95;
        /// 0x96 - ExtraShouldWear
        const ShouldWear = 0x96;
        /// 0x97 - ExtraFavorCost
        const FavorCost = 0x97;
        /// 0x98 - ExtraAttachedArrows3D
        const AttachedArrows3D = 0x98;
        /// 0x99 - ExtraTextDisplayData
        const TextDisplayData = 0x99;
        /// 0x9A - ExtraAlphaCutoff
        const AlphaCutoff = 0x9A;
        /// 0x9B - ExtraEnchantment
        const Enchantment = 0x9B;
        /// 0x9C - ExtraSoul
        const Soul = 0x9C;
        /// 0x9D - ExtraForcedTarget
        const ForcedTarget = 0x9D;
        /// 0x9E
        const Unk9E = 0x9E;
        /// 0x9F - ExtraUniqueID
        const UniqueID = 0x9F;
        /// 0xA0 - ExtraFlags
        const Flags = 0xA0;
        /// 0xA1 - ExtraRefrPath
        const RefrPath = 0xA1;
        /// 0xA2 - ExtraDecalGroup
        const DecalGroup = 0xA2;
        /// 0xA3 - ExtraLockList
        const LockList = 0xA3;
        /// 0xA4 - ExtraForcedLandingMarker
        const ForcedLandingMarker = 0xA4;
        /// 0xA5 - ExtraLargeRefOwnerCells
        const LargeRefOwnerCells = 0xA5;
        /// 0xA6 - ExtraCellWaterEnvMap
        const CellWaterEnvMap = 0xA6;
        /// 0xA7 - ExtraCellGrassData
        const CellGrassData = 0xA7;
        /// 0xA8 - ExtraTeleportName
        const TeleportName = 0xA8;
        /// 0xA9 - ExtraInteraction
        const Interaction = 0xA9;
        /// 0xAA - ExtraWaterData
        const WaterData = 0xAA;
        /// 0xAB - ExtraWaterCurrentZoneData
        const WaterCurrentZoneData = 0xAB;
        /// 0xAC - ExtraAttachRef
        const AttachRef = 0xAC;
        /// 0xAD - ExtraAttachRefChildren
        const AttachRefChildren = 0xAD;
        /// 0xAE - ExtraGroupConstraint
        const GroupConstraint = 0xAE;
        /// 0xAF - ExtraScriptedAnimDependence
        const ScriptedAnimDependence = 0xAF;
        /// 0xB0 - ExtraCachedScale
        const CachedScale = 0xB0;
        /// 0xB1 - ExtraRaceData
        const RaceData = 0xB1;
        /// 0xB2 - ExtraGIDBuffer
        const GIDBuffer = 0xB2;
        /// 0xB3 - ExtraMissingRefIDs
        const MissingRefIDs = 0xB3;
        /// 0xB4
        const UnkB4 = 0xB4;
        /// 0xB5 - ExtraResourcesPreload
        const ResourcesPreload = 0xB5;
        /// 0xB6
        const UnkB6 = 0xB6;
        /// 0xB7
        const UnkB7 = 0xB7;
        /// 0xB8
        const UnkB8 = 0xB8;
        /// 0xB9
        const UnkB9 = 0xB9;
        /// 0xBA
        const UnkBA = 0xBA;
        /// 0xBB
        const UnkBB = 0xBB;
        /// 0xBC
        const UnkBC = 0xBC;
        /// 0xBD
        const UnkBD = 0xBD;
        /// 0xBE
        const UnkBE = 0xBE;
        /// 0xBF
        const UnkBF = 0xBF;
    }
}
