[package]
name = "commonlibsse_ng_derive_internal"
description = "Change the root crate name `commonlibsse_ng` to `crate` to allow the library itself to use the proc macro. This is not intended for user use."
version = "0.1.0"

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme = "./readme.md"
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true


[dependencies]
commonlibsse_ng_proc_macro_common = { path = "../commonlibsse_ng_proc_macro_common" }
syn = { version = "2.0.99" }
quote = { version = "1.0.39" }

[features]
tracing = ["commonlibsse_ng_proc_macro_common/tracing"]
