name: Release(prebuilt)

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: 7f9f0e44db287e8e67c0e888141bfa200ab45121
      - name: Cache
        uses: actions/cache@v4.2.0
        with:
          path: |
            vcpkg_installed
            build
          key: |
            vcpkg-windows-x64-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
      - name: Install
        run: vcpkg install

      - name: Zip
        shell: pwsh
        run: |
          mkdir -p ./build/vcpkg_installed/x64-windows/;
          Move-Item -Path ./vcpkg_installed/x64-windows/include -Destination './build/vcpkg_installed/x64-windows'
          Move-Item -Path ./vcpkg_installed/x64-windows/lib     -Destination './build/vcpkg_installed/x64-windows'
          Move-Item -Path ./vcpkg_installed/x64-windows/share   -Destination './build/vcpkg_installed/x64-windows'
          Compress-Archive -Path './build/*' -DestinationPath './CommonLibSSE-NG-prebuilt.zip'

      - name: Release
        uses: ncipollo/release-action@v1.15.0
        with:
          allowUpdates: true
          artifacts: ./CommonLibSSE-NG-prebuilt.zip
