on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: 1b279b20c7e0db1c9d549ff3b64e024c01317b55

      - name: Build CommonLibSSE-NG
        run: vcpkg install

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: CommonLibSSE-NG
          path: |
            ./vcpkg_installed/x64-windows/include
            ./vcpkg_installed/x64-windows/lib
            !./vcpkg_installed/x64-windows/lib/CommonLibSSE-NG/
            ./vcpkg_installed/x64-windows/share

      # - name: Release
      #   uses: ncipollo/release-action@v1.15.0
      #   with:
      #     allowUpdates: true
      #     artifacts: |
      #       ./vcpkg_installed/x64-windows/include
      #       ./vcpkg_installed/x64-windows/lib
      #       !./vcpkg_installed/x64-windows/lib/CommonLibSSE-NG/
      #       ./vcpkg_installed/x64-windows/share
